name: jdb

on:
  repository_dispatch:
    types: jdb
  workflow_dispatch:
  #schedule:
    #- cron: 00 23 * * *

env:
  UPLOAD_RELEASE: true
  FILE_NAME: jdb

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:    
    - name: Checkout
      uses: actions/checkout@main
    - name: 打包镜像
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: https://github.com/binge8/op/releases/download/3jarmv8/openwrt-armvirt-64-default-rootfs.tar.gz
        KERNEL_VERSION_NAME: 5.15.2_5.17.2
    - name: upload release
      if: env.UPLOAD_RELEASE == 'true' && env.PACKAGED_STATUS == 'success'
      uses: ncipollo/release-action@v1
      with:
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        allowUpdates: true
        tag: 3jarmv8
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
    - name: #微信推送
      if: always()
      run: |
        if [ "${{ env.compile }}" = "success" ];then
          curl -H "Content-Type:application/json" -X POST -d '{"token":"${{ secrets.pushbot }}","title":"${{ env.FILE_NAME }}成功","content":"${{ env.FILE_NAME }}发布成功","template":"json"}' http://www.pushplus.plus/send
        else
          curl -H "Content-Type:application/json" -X POST -d '{"token":"${{ secrets.pushbot }}","title":"${{ env.FILE_NAME }}失败","content":"${{ env.FILE_NAME }}发布失败","template":"json"}' http://www.pushplus.plus/send
        fi